apps/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostsView.as_view()),
    path("filter/", views.FilterPostsView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMovPostView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("author/<str:slug>/", views.AuthorView.as_view(), name="author_detail"),

    path('post/add/', views.PostCreate.as_view(), name='post_create'),
    path('<slug:slug>/edit/', views.PostUpdate.as_view(), name='post_edit'),
    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post_delete'),

]

django_board/urls.py
"""django_board URL Configuration
"""
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path("", include("apps.urls")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

templates/include/footer.html
{% load contact_tags %}
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true">
                                    Django School
                                </span>
                    </a>
                </h2>
                <p class="editContent">
                    Канал для программистов и людей, которые хотят развиваться в сфере IT.
                    Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                    и многое другое.
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent">
                            <span class="fa fa-facebook-f"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent">
                            <span class="fa fa-twitter"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent">
                            <span class="fa fa-dribbble"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent">
                            <span class="fa fa-google-plus"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    {% contact_form %}
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                            Разделы</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="http://127.0.0.1:8000/" class="editContent">Главная</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent">Категории</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent">Контакты</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                                Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">
                            Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent">Email </h4>
                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a>
                                </p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent">Location</h4>
                                <p class="editContent">New York City</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2019 - 2020 DjangoMovie. All rights reserved | Design by
                <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
            </p>
            <!-- move top icon -->
            <a href="#home" class="move-top text-right col-md-2"><span
                    class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
            <!-- //move top icon -->
        </div>
    </div>
</div>

templates/include/header.html
{% load i18n post_tag %}
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1><a href="http://127.0.0.1:8000/ru/" class="editContent"
                       style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: Source Sans Pro;, sans-serif;">Django</a>
                </h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="http://127.0.0.1:8000/">Главная</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Категории <span
                            class="fa fa-angle-down" aria-hidden="true"></span> </label>
                    <a href="#">Категории <span class="fa fa-angle-down"
                                                aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        {% get_categories as categories %}
                        {% for category in categories %}
                            <li><a href="/">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    {% if user.is_authenticated %}

                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <span>{{ user.username }}</span>

                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                            </li>
                            {% if user.is_superuser or user.is_staff %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                        Админ-панель
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'post_create' %}">
                                    Создать объявление
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                        <a href="{% url 'users:login' %}"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                            Вход
                        </a>
                         <a href="{% url 'users:registration' %}"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                            Регистрация
                        </a>
                    {% endif %}
                </li>

                <li>
                    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                        <input name="next" type="hidden" value="{{ language.code }}/{{ request.get_full_path|slice:'4:' }}">
                        <select name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                        selected{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="Go">
                    </form>
                </li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
<!-- //header -->
<!--/banner-->
<div class="banner-info">
    <p class="editContent">лучший сайт на django 3</p>
    <h3 class="mb-4 editContent">Все о играх</h3>
    <div class="ban-buttons">


    </div>
</div>
<!--// banner-inner -->

templates/include/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        {% if page_obj.number|add:'-3' > 1 %}
            <li class="pagination__item">
                <a href="?{{ q }}{{ genre }}{{ year }}page=1">1</a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'-3' >= 3 %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.previous_page_number|add:'-3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
    {% if paginator.page_range|length > 1 %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="pagination__item active">
                    <a class="pagination__link" href="#">{{ i }}</a>
                </li>
            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                <li class="pagination__item">
                        <a class="pagination__link" href="?{{ q }}{{ genre }}{{ year }}page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if page_obj.has_next %}
        {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.next_page_number|add:'3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
            <li class="pagination__item">
                    <a class="pagination__link" href="?{{ q }}{{ genre }}{{ year }}page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                    </a>
            </li>
        {% endif %}
    {% endif %}
</ul>

templates/include/sidebar.html
{% load post_tag %}
<div class="search-bar w3layouts-newsletter">
    <h3 class="sear-head editContent">Поиск фильма</h3>
    <form action="{% url 'search' %}" method="get" class="d-flex editContent">
        <input type="search" placeholder="Введите название..." name="q" class="form-control" required="">
        <button type="submit" class="btn1 btn">
            <span class="fa fa-search" aria-hidden="true"></span>
        </button>
    </form>
</div>
<!--preference -->
<form action="{% url 'filter' %}" method="get" name="filter">
    <div class="left-side my-4">
        <h3 class="sear-head editContent">Классы</h3>
        <ul class="w3layouts-box-list">
            {% for class in view.get_ClassMMORPG %}
                <li class="editContent">
                    <input type="checkbox" class="checked" name="ClassMMORPG" value="{{ ClassMMORPG.id }}">
                    <span class="span editContent">{{ class.name }}</span>
                </li>
            {% endfor %}
        </ul>

    </div>
    <!-- // preference -->
    <!-- discounts -->

    <div class="left-side">
        <h3 class="sear-head editContent">Категории</h3>
        <ul class="w3layouts-box-list">
            {% for categor in view.get_category %}
                <li class="editContent">
                    <input type="checkbox" class="checked" name="category" value="{{ categor.name }}">
                    <span class="span editContent">{{ categor.name }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <button type="submit">Найти</button>
</form>
<!-- //discounts -->
<!-- reviews -->
<div class="customer-rev left-side my-4">
    <h3 class="sear-head editContent">Рейтинг</h3>
    <ul class="w3layouts-box-list">
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="editContent">5.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">4.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.5</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">2.5</span>
            </a>
        </li>
    </ul>
</div>
{% get_last_post count=3 %}